# Generated by Django 3.1.3 on 2020-11-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommender',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_from_user', to='user.user'),
        ),
        migrations.AddField(
            model_name='recommender',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_to_user', to='user.user'),
        ),
    ]
