# Generated by Django 3.1.3 on 2020-11-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20201108_1133'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recommendation',
            table='recommendation',
        ),
    ]
