# Generated by Django 3.1.3 on 2020-11-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_auto_20201108_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommender',
            name='contents',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
