# Generated by Django 3.1.3 on 2020-11-04 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('likes_count', models.IntegerField(default=0)),
                ('contents', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=200)),
                ('deadline', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender', models.FloatField()),
                ('applicant', models.FloatField()),
            ],
            options={
                'db_table': 'compensations',
            },
        ),
        migrations.CreateModel(
            name='ExploreMainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'explore_main_categories',
            },
        ),
        migrations.CreateModel(
            name='ExploreSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.exploremaincategory')),
            ],
            options={
                'db_table': 'explore_sub_categories',
            },
        ),
        migrations.CreateModel(
            name='ResponseRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'response_rates',
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tag_categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.tagcategory')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=0)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.career')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.exploremaincategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.exploresubcategory')),
            ],
            options={
                'db_table': 'salaries',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.city')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='CompanyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.tag')),
            ],
            options={
                'db_table': 'company_tags',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='company_tag',
            field=models.ManyToManyField(related_name='company_tags', through='company.CompanyTag', to='company.Tag'),
        ),
        migrations.AddField(
            model_name='company',
            name='compensation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.compensation'),
        ),
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.district'),
        ),
        migrations.AddField(
            model_name='company',
            name='explore_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.exploresubcategory'),
        ),
        migrations.AddField(
            model_name='company',
            name='response_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.responserate'),
        ),
    ]
