# Generated by Django 3.1.3 on 2020-11-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='year_of_service',
        ),
        migrations.RemoveField(
            model_name='education',
            name='year_of_service',
        ),
        migrations.RemoveField(
            model_name='usercareer',
            name='year_of_service',
        ),
        migrations.AddField(
            model_name='award',
            name='date',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_data',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercareer',
            name='end_data',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercareer',
            name='start_date',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
