# Generated by Django 3.1.3 on 2020-11-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20201107_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='usercareer',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
